### ISSUE TITLE
Missing BtcTransmuter.Extensions

### ISSUE THREAD

**Issue by rockstardev** [Kukks/btcTransmuter-vnext#1]
Last commit seems to exclude class that's in this namespace which breaks the build.

https://github.com/Kukks/btcTransmuter-vnext/commit/10db2436bf2f248ad886fa398b1b55cb032768cb#diff-b2b8cc12a03235ddfb60ea7c095ca2d6R9

Result:

![build-breaking](https://user-images.githubusercontent.com/5191402/54255533-7ecdc880-4526-11e9-9e05-7454c8698a74.jpg)

**Comment by Kukks** [comment]
fixed in #a09ad2967192eb853b21356e49d29c1c40116651
