### ISSUE TITLE
BtcPayServer invoices keep triggering after action on them is executed

### ISSUE THREAD

**Issue by rockstardev** [Kukks/btcTransmuter-vnext#3]
I have single recipe that takes BtcPayServer `invoices.Status == "paid"` and triggers action to place Order on the exchange.

When action executes and is entered in log, I don't expect trigger to keep working for that same recipe... yet it does... here is screenshot of code executing trigger hours after action was taken for certain invoice.

![invoice triggered](https://user-images.githubusercontent.com/5191402/54327723-1b50a300-45d9-11e9-9d2e-0d3096b90a8b.png)

Obviously what should happen, and is expected behavior -> once action(s) are taken once on certain invoice triggers = do not evaluate those same invoices again and again for possible triggers.

**Comment by Kukks** [comment]
This is actually by design after checking it out. The trigger will always trigger as long as its status has changed. It is up to the Trigger handler(in this case `NBXplorerNewTransactionTriggerHandler`) to validate whether it triggers any recipes though.

**Comment by Kukks** [comment]
One example of this is if you have 2 recipes with an invoice status trigger. One of them is set for pending while the other is for Completed. The event needs to trigger for each status change in order to hit both recipes.
